#                                           Rock vs Mine Prediction

In [269]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
df=pd.read_csv('/Users/vaishalisingh/Desktop/sonar_data.csv')
df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

In [254]:
df.describe()

0.0200      0.0371      0.0428      0.0207      0.0954      0.0986  \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.029208    0.038443    0.043837    0.054053    0.075105    0.104599   
std      0.023038    0.033040    0.038521    0.046583    0.055669    0.059247   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013300    0.016400    0.018900    0.024450    0.037700    0.066950   
50%      0.022800    0.030800    0.034200    0.044100    0.062000    0.092100   
75%      0.035800    0.048100    0.058200    0.065700    0.101050    0.134150   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

           0.1539      0.1601      0.3109      0.2111  ...      0.0232  \
count  207.000000  207.000000  207.000000  207.000000  ...  207.000000   
mean     0.121591    0.134677    0.177361    0.208245  ...    0.016034   
std      0.061897    0.085340    0.118311    0.134741  ...    0.012027   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080600    0.080350    0.096750    0.111150  ...    0.008350   
50%      0.105600    0.111900    0.152200    0.181000  ...    0.013800   
75%      0.153050    0.169800    0.231500    0.269000  ...    0.020700   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

           0.0027      0.0065      0.0159      0.0072      0.0167      0.0180  \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.013472    0.010729    0.010917    0.009300    0.008181    0.007771   
std      0.009628    0.007071    0.007310    0.007103    0.005719    0.005756   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007350    0.005050    0.005350    0.004100    0.004400    0.003700   
50%      0.011500    0.009600    0.009300    0.007500    0.006800    0.005900   
75%      0.016750    0.014900    0.014450    0.012100    0.010350    0.010350   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

           0.0084      0.0090      0.0032  
count  207.000000  207.000000  207.000000  
mean     0.007947    0.007936    0.006523  
std      0.006485    0.006196    0.005038  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003650    0.003100  
50%      0.005800    0.006300    0.005300  
75%      0.010400    0.010350    0.008550  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [255]:
x=df.drop(df.columns[60], axis='columns')
x.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  \
0  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
1  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
2  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
3  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
4  0.3039  ...  0.0104  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057   

   0.0084  0.0090  0.0032  
0  0.0049  0.0052  0.0044  
1  0.0164  0.0095  0.0078  
2  0.0044  0.0040  0.0117  
3  0.0048  0.0107  0.0094  
4  0.0027  0.0051  0.0062  

[5 rows x 60 columns]

In [256]:
y=df.R
y

0      R
1      R
2      R
3      R
4      R
      ..
202    M
203    M
204    M
205    M
206    M
Name: R, Length: 207, dtype: object

In [257]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

## Model Selection

In [258]:
model_1=cross_val_score(LogisticRegression(random_state=2),x,y)
print(model_1)
print(np.mean(model_1))

[0.4047619  0.78571429 0.63414634 0.85365854 0.48780488]
0.6332171893147502


In [259]:
model_2=cross_val_score(SVC(kernel="linear",random_state=2),x,y)
print(model_2)
print(np.mean(model_2))

[0.4047619  0.76190476 0.68292683 0.85365854 0.48780488]
0.6382113821138211


In [260]:
model_3=cross_val_score(tree.DecisionTreeClassifier(splitter="random",random_state=2),x,y)
print(model_3)
print(np.mean(model_3))

[0.57142857 0.71428571 0.56097561 0.7804878  0.58536585]
0.6425087108013938


In [262]:
model_4=cross_val_score(RandomForestClassifier(random_state=2),x,y)
print(model_4)
print(np.mean(model_4))

[0.52380952 0.80952381 0.70731707 0.80487805 0.65853659]
0.7008130081300814


### Random Forest had the better score 
## Applying random forest on the dataset:

In [263]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)

In [264]:
model=RandomForestClassifier(random_state=2)
model.fit(x_train,y_train)

RandomForestClassifier(random_state=2)

## Model Evaluation

In [276]:
x_train_prediction=model.predict(x_train)
training_accuracy=accuracy_score(x_train_prediction,y_train)
print('Accuracy on training data: ',training_accuracy)

Accuracy on training data:  1.0


In [274]:
x_test_prediction=model.predict(x_test)
testing_accuracy=accuracy_score(x_test_prediction,y_test)
print('Accuracy on testing data: ',testing_accuracy)

Accuracy on testing data:  0.9047619047619048


In [275]:
print('Model Score: ',model.score(x_test,y_test))

Model Score:  0.9047619047619048


## Predictive System

In [266]:
input_data=(0.0307,0.0523,0.0653,0.0521,0.0611,0.0577,0.0665,0.0664,0.1460,0.2792,0.3877,0.4992,0.4981,0.4972,0.5607,0.7339,0.8230,0.9173,0.9975,0.9911,0.8240,0.6498,0.5980,0.4862,0.3150,0.1543,0.0989,0.0284,0.1008,0.2636,0.2694,0.2930,0.2925,0.3998,0.3660,0.3172,0.4609,0.4374,0.1820,0.3376,0.6202,0.4448,0.1863,0.1420,0.0589,0.0576,0.0672,0.0269,0.0245,0.0190,0.0063,0.0321,0.0189,0.0137,0.0277,0.0152,0.0052,0.0121,0.0124,0.0055)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)

if(prediction[0]=='M'):
    print('the object is a Mine')
else:
    print('the object is a Rock')

['M']
the object is a Mine


/Users/vaishalisingh/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
